
sudo: required

matrix:
  include:
    - name: "Ubuntu bionic (18.04)"
      os: linux
      dist: bionic
      language: python
      python: 3.7
      before_install:
        - export PY3="python3"
        - export SUDO="sudo"
        - wget https://bootstrap.pypa.io/get-pip.py
        - $SUDO $PY3 get-pip.py
      addons:
        homebrew:
          packages:
            - python3-gevent

    - name: "OSX"
      os: osx
      osx_image: xcode11
      language: generic
      python: "3.7"
      before_install:
        - export SUDO="sudo"
        - export PY3="python3.7"
        - wget https://www.python.org/ftp/python/3.7.3/python-3.7.3-macosx10.9.pkg
        - $SUDO installer -pkg python-3.7.3-macosx10.9.pkg -target /
        - wget https://bootstrap.pypa.io/get-pip.py
        - $PY3 get-pip.py

      addons:
        homebrew:
          packages:
            - pkg-config
            - python3-dev
            - python3-gevent

    - name: "Windows"
      os: windows
      language: sh
      python: "3.7"
      before_install:
        - export PY3="/c/python37/python.exe"
        - export SUDO=""
        - choco install python3
        - $PY3 -m pip install --upgrade pip

script:
  - $SUDO $PY3 -m pip install --upgrade setuptools
  # - $SUDO $PY3 setup.py build --dev --DISTUTILS_DEBUG
  - $SUDO $PY3 setup.py install bdist_wheel build_docs --dev
