jobs:
  - ${{ each image in parameters.images }}:
    - ${{ each pythonVersion in parameters.pythonVersions }}:
      - job:
        displayName: ${{ format('OS:{0} PY:{1}', image, pythonVersion) }}

        pool:
          vmImage: ${{ image }}

        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: ${{ pythonVersion }}
              addToPath: true
          - script: python -m pip install --upgrade pip setuptools wheel
            displayName: 'Install tools'

          - script: python -m pip install -r build_requirements.txt
            displayName: 'Install build requirements'

          - script: python setup.py build --service
            displayName: 'build --service'

          - script: python setup.py build_docs
            displayName: 'build_docs'

          - script: python setup.py bdist_wheel --service
            displayName: 'bdist_wheel --service'

          - script: python setup.py install --service
            displayName: 'install --service'

          - script: python setup.py build --service --cython
            displayName: 'build --service --cython'

          - script: python setup.py bdist_wheel --cython --service
            displayName: 'bdist_wheel --cython --service'

