trigger:
  branches:
    include:
      - master
      -
jobs:
- job: 'libopenzwave'
  strategy:
    matrix:
      maxParallel: 2

      linux:
        imageName: 'ubuntu-latest'
      mac:
        imageName: 'macOS-latest'
      windows:
        imageName: 'windows-latest'

      Python36:
        python.version: '3.6'
      Python37:
          python.version: '3.7'
      Python38:
          python.version: '3.8'
      Python39:
          python.version: '3.9'
      Python310:
          python.version: '3.10'


  steps:
    - checkout: self
      submodules: recursive

    - task: UsePythonVersion@0
      displayName: 'Use Python $(python.version)'
      inputs:
        versionSpec: '$(python.version)'

      - script: python -m pip install --upgrade pip setuptools wheel
        displayName: 'Install tools'


    - task: PublishTestResults@2
        inputs:
          testResultsFiles: 'reports/django-basic.xml'
          testRunTitle: '$(Agent.OS) - $(Build.DefinitionName) - Python $(python.version)'
          condition: succeededOrFailed()