jobs:
  - template: azure-pipelines-linux.yml
    parameters:
      images:
        - 'ubuntu-22.04'
        - 'ubuntu-20.04'
      pythonVersions:
        - '3.8'
        - '3.9'
        - '3.10'
  
  - template: azure-pipelines-windows.yml
    parameters:
      images:
        - 'windows-2022'
        - 'windows-2019'
      pythonVersions:
        - '3.8'
        - '3.9'
        - '3.10'

  - template: azure-pipelines-mac.yml
    parameters:
      images:
        - 'macOS-12'
        - 'macOS-11'
      pythonVersions:
        - '3.8'
        - '3.9'
        - '3.10'




