jobs:
  - ${{ each image in parameters.images }}:
    - ${{ each pythonVersion in parameters.pythonVersions }}:
      - job:
        displayName: ${{ format('OS:{0} PY:{1}', image, pythonVersion) }}

        pool:
          vmImage: ${{ image }}

        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: ${{ pythonVersion }}
              addToPath: true
          - script: python -m pip install --upgrade pip setuptools wheel
            displayName: 'Install tools'

          - script: python -m pip install -r build_requirements.txt
            displayName: 'Install build requirements'

          - script: python setup.py build --service --dev
            displayName: 'build --service --dev'

          - script: python setup.py bdist-wheel --service --dev
            displayName: 'bdist-wheel --service --dev'

          - script: python setup.py install --service --dev
            displayName: 'install --service --dev'

          - script: python setup.py build --service --cython --dev
            displayName: 'build --service --cython --dev'

          - script: python setup.py bdist_wheel --cython --service --dev
            displayName: 'bdist_wheel --cython --service --dev'

          - script: python setup.py build-docs
            displayName: 'build-docs'
